package com.xc.entity;

public class Person {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.person.id
     *
     * @mbggenerated Sun May 28 11:49:57 JST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.person.name
     *
     * @mbggenerated Sun May 28 11:49:57 JST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.person.age
     *
     * @mbggenerated Sun May 28 11:49:57 JST 2017
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.person.sex
     *
     * @mbggenerated Sun May 28 11:49:57 JST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.person.password
     *
     * @mbggenerated Sun May 28 11:49:57 JST 2017
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.person.id
     *
     * @return the value of public.person.id
     *
     * @mbggenerated Sun May 28 11:49:57 JST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.person.id
     *
     * @param id the value for public.person.id
     *
     * @mbggenerated Sun May 28 11:49:57 JST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.person.name
     *
     * @return the value of public.person.name
     *
     * @mbggenerated Sun May 28 11:49:57 JST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.person.name
     *
     * @param name the value for public.person.name
     *
     * @mbggenerated Sun May 28 11:49:57 JST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.person.age
     *
     * @return the value of public.person.age
     *
     * @mbggenerated Sun May 28 11:49:57 JST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.person.age
     *
     * @param age the value for public.person.age
     *
     * @mbggenerated Sun May 28 11:49:57 JST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.person.sex
     *
     * @return the value of public.person.sex
     *
     * @mbggenerated Sun May 28 11:49:57 JST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.person.sex
     *
     * @param sex the value for public.person.sex
     *
     * @mbggenerated Sun May 28 11:49:57 JST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.person.password
     *
     * @return the value of public.person.password
     *
     * @mbggenerated Sun May 28 11:49:57 JST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.person.password
     *
     * @param password the value for public.person.password
     *
     * @mbggenerated Sun May 28 11:49:57 JST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }
}